 // Author: Sai Sindhu Bhimavarapu

const TravelPackages = [
    {
    id: 1,
    title: "Halifax",
    location: "Halifax, Nova Scotia",
    cost: 1000,
    rating: 4.9,
    description: "Halifax, an Atlantic Ocean port in eastern Canada, is the provincial capital of Nova Scotia. A major business centre, it’s also known for its maritime history. The city’s dominated by the hilltop Citadel, a star-shaped fort completed in the 1850s. ",
}, {
    id: 1,
    title: "Montreal",
    location: "Montreal, Quebec",
    cost: 750,
    rating: 4.8,
    description: "Montreal is the largest city in Canada's Québec province. It’s set on an island in the Saint Lawrence River and named after Mt. Royal, the triple-peaked hill at its heart. Its boroughs, many of which were once independent cities, include neighbourhoods ranging from cobblestoned, French colonial Vieux-Montréal – with the Gothic Revival Notre-Dame Basilica at its centre – to bohemian Plateau.",
}, {
    id: 1,
    title: "Windsor",
    location: "Windsor, Ontario",
    cost: 400,
    rating: 4.5,
    description: "Windsor is a city in Ontario, Canada, situated on the south bank of the Detroit River directly across from Detroit, Michigan. Located in Essex County, it is the southernmost city in Canada and marks the southwestern end of the Quebec City–Windsor Corridor.",
},{
      id: 1,
      title: "Halifax",
      location: "Halifax, Nova Scotia",
      cost: 1000,
      rating: 4.9,
      description: "Halifax, an Atlantic Ocean port in eastern Canada, is the provincial capital of Nova Scotia. A major business centre, it’s also known for its maritime history. The city’s dominated by the hilltop Citadel, a star-shaped fort completed in the 1850s. ",
    },
    {
      id: 2,
      title: 'Montreal',
      location: "Halifax, Nova Scotia",
      cost: 1500,
      rating: 4.7,
      description: 'Enchanting European Forest Retreat: Discover a Serene Nature Haven with Breathtaking Scenery',
    },
    {
      id: 3,
      title: 'Charming Evening Delights',
      location: 'Halifax, Nova Scotia',
      cost: 2000,
      rating: 4.5,
      description: 'Experience the Vibrant Downtown Views, Savor Chai, Seafood, and More in Captivating Canada',
    },
    {
      id: 4,
      title: 'Majestic Aerial Panorama',
      location: ' Australia',
      cost: 4920,
      rating: 4.2,
      description: 'Explore the World Grandest Bird Eye View in Australia',
    },
    {
      id: 5,
      title: 'Timeless Treasures Unveiled',
      location: 'London, United Kingdom',
      cost: 2000,
      rating: 4.8,
      description: 'Discover London Renowned Museum with Ancient Artifacts Dating Back 2000 Years',
    },
    {
      id: 6,
      title: 'Inspiration Unleashed',
      location: 'China',
      cost: 2000,
      rating: 4.6,
      description: 'Immerse Yourself in a Haven for Artists, Showcasing a Diverse Collection of Over 100 Masterful Painting',
    },
    {
      id: 7,
      title: 'Unforgettable Journey to Egypt Pyramids',
      location: 'Egypt',
      cost: 4920,
      rating: 4.3,
      description: 'Embark on a Lifetime Adventure Amidst Iconic Wonders',
    },
    {
      id: 8,
      title: 'Romantic Getaway by the Seaside',
      location: 'Halifax, Nova Scotia',
      cost: 2000,
      rating: 4.9,
      description: 'Experience an Unforgettable Date Night Amidst Breathtaking Beachscape',
    },
    {
      id: 9,
      title: 'Snowy Splendor',
      location: 'Majestic Mountains',
      cost: 2000,
      rating: 4.7,
      description: 'Embrace the Beauty of Majestic Mountains with a Perfect Blend of Scenic Grandeur and Gentle Chill',
    },
    {
      id: 10,
      title: 'Elevated Serenity',
      location: 'Atlantica',
      cost: 2000,
      rating: 4.4,
      description: 'Witness the Iconic Hill Views from a Majestic Hot Air Balloon Ride',
    },
    {
      id: 11,
      title: 'Garden of Enchantment',
      location: 'Dream-like Temple Garden',
      cost: 2000,
      rating: 4.6,
      description: 'Embark on an Unforgettable Adventure Through a Dream-like Temple Garden',
    },
    {
      id: 12,
      title: 'Tropical Paradise Retreat',
      location: 'Beachside Escape',
      cost: 2000,
      rating: 4.8,
      description: 'Immerse Yourself in the Best Beachside Escape, Serenaded by the Melody of Waves',
    },
  ];

export {TravelPackages};